/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import app.properties.BidTransactionBlock;
import app.properties.Block;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void printBlockJson() {
        Block a = new BidTransactionBlock(
                "a blockHash",
                "a previousBlockHash",
                1, 2, 3,
                "a receiverAddress",
                "a publicKeySender",
                "a publicKeyReceiver",
                4, 5, 6, new byte[1]);
        System.out.println(a.toJson());
    }
}
